In [2]:
import numpy as np
import pandas as pd
poke = pd.read_csv("./pokemon_data.csv")
poke.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [3]:
poke

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [5]:
poke.tail()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [9]:
poke.iloc[1:3]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

In [11]:
poke['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [12]:
poke['Name'][0:5]

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [16]:
poke[['Name', 'HP','Speed']][15:25]

                     Name  HP  Speed
15             Butterfree  60     70
16                 Weedle  40     50
17                 Kakuna  45     35
18               Beedrill  65     75
19  BeedrillMega Beedrill  65    145
20                 Pidgey  40     56
21              Pidgeotto  63     71
22                Pidgeot  83    101
23    PidgeotMega Pidgeot  83    121
24                Rattata  30     72

In [17]:
poke.loc[poke['Type 1'] == 'Rock']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
80,74,Geodude,Rock,Ground,40,80,100,30,30,20,1,False
81,75,Graveler,Rock,Ground,55,95,115,45,45,35,1,False
82,76,Golem,Rock,Ground,80,120,130,55,65,45,1,False
103,95,Onix,Rock,Ground,35,45,160,30,45,70,1,False
149,138,Omanyte,Rock,Water,35,40,100,90,55,35,1,False
150,139,Omastar,Rock,Water,70,60,125,115,70,55,1,False
151,140,Kabuto,Rock,Water,30,80,90,55,45,55,1,False
152,141,Kabutops,Rock,Water,60,115,105,65,70,80,1,False
153,142,Aerodactyl,Rock,Flying,80,105,65,60,75,130,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False
200,185,Sudowoodo,Rock,NaN,70,100,115,30,65,30,2,False
265,246,Larvitar,Rock,Ground,50,64,50,45,50,41,2,False
266,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False
267,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False
323,299,Nosepass,Rock,NaN,30,45,135,45,90,30,3,False
369,337,Lunatone,Rock,Psychic,70,55,65,95,85,70,3,False
370,338,Solrock,Rock,Psychic,70,95,85,55,65,70,3,False
377,345,Lileep,Rock,Grass,66,41,77,61,87,23,3,False
378,346,Cradily,Rock,Grass,86,81,97,81,107,43,3,False
379,347,Anorith,Rock,Bug,45,95,50,40,50,75,3,False
380,348,Armaldo,Rock,Bug,75,125,100,70,80,45,3,False
414,377,Regirock,Rock,NaN,80,100,200,50,100,50,3,True
453,408,Cranidos,Rock,NaN,67,125,40,30,30,58,4,False
454,409,Rampardos,Rock,NaN,97,165,60,65,50,58,4,False
455,410,Shieldon,Rock,Steel,30,42,118,42,88,30,4,False
456,411,Bastiodon,Rock,Steel,60,52,168,47,138,30,4,False
486,438,Bonsly,Rock,NaN,50,80,95,10,45,10,4,False
528,476,Probopass,Rock,Steel,60,55,145,75,150,40,4,False
583,524,Roggenrola,Rock,NaN,55,75,85,25,25,15,5,False
584,525,Boldore,Rock,NaN,70,105,105,50,40,20,5,False
585,526,Gigalith,Rock,NaN,85,135,130,60,80,25,5,False
627,566,Archen,Rock,Flying,55,112,45,74,45,70,5,False
628,567,Archeops,Rock,Flying,75,140,65,112,65,110,5,False
700,639,Terrakion,Rock,Fighting,91,129,90,72,90,108,5,True
758,688,Binacle,Rock,Water,42,52,67,39,56,50,6,False
759,689,Barbaracle,Rock,Water,72,105,115,54,86,68,6,False
766,696,Tyrunt,Rock,Dragon,58,89,77,45,45,48,6,False
767,697,Tyrantrum,Rock,Dragon,82,121,119,69,59,71,6,False
768,698,Amaura,Rock,Ice,77,59,50,67,63,46,6,False
769,699,Aurorus,Rock,Ice,123,77,72,99,92,58,6,False
773,703,Carbink,Rock,Fairy,50,50,150,50,150,50,6,False
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True